name: app_b
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.4
  lottie: ^3.2.0
  image_picker: ^1.1.2
  file_picker: ^9.2.2
  speech_to_text: ^7.0.0
  avatar_glow: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/




fonts:
  - family: bold
    fonts:
      - asset: assets/fonts/Poppins-Bold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  - family: regular
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package